FROM golang:bullseye AS builder
RUN apt update && apt install build-essential -y
WORKDIR /go/livetv_src
COPY . . 
RUN go build -o livetv .

FROM debian:bullseye-slim
RUN apk --no-cache add ca-certificates libc6-compat libgcc libstdc++
WORKDIR /opt
COPY --from=builder /go/livetv_src/livetv .
EXPOSE 9000
VOLUME ["/opt/data"]
CMD ["./livetv"]